const char certStr[] = {
    "-----BEGIN CERTIFICATE-----\n"
    "MIIDtTCCAp2gAwIBAgIUNSvXXqsVgRE8jnh+0OpxwE/H3eUwDQYJKoZIhvcNAQEL\n"
    "BQAwajELMAkGA1UEBhMCY24xEDAOBgNVBAgMB0JlaUppbmcxETAPBgNVBAcMCENo\n"
    "YW9ZYW5nMREwDwYDVQQKDAhwZXJzb25hbDERMA8GA1UECwwIcGVyc29uYWwxEDAO\n"
    "BgNVBAMMB21xdHQtbGgwHhcNMjUwODI5MDIwNzA5WhcNMzUwODI3MDIwNzA5WjBq\n"
    "MQswCQYDVQQGEwJjbjEQMA4GA1UECAwHQmVpSmluZzERMA8GA1UEBwwIQ2hhb1lh\n"
    "bmcxETAPBgNVBAoMCHBlcnNvbmFsMREwDwYDVQQLDAhwZXJzb25hbDEQMA4GA1UE\n"
    "AwwHbXF0dC1saDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAO6pdH1n\n"
    "yBk6xpytnzNXraDqjPAlF0zHzM3LInYBzaldUXN4j0kDdT6zpDTufUgytGtP3epi\n"
    "QzO+Hc6g9w/8pdYxsPkfWUgHfJZeKHAI148+s3ZsmvgAmrPM1CMLoJfriNL2m3vc\n"
    "MJyZAR2KKG6StegaME1rLLhqCVwnW9sm1XWSe1+DNd1CeTj49+RIolq0xHlQfUGb\n"
    "sukJ1UqiruZd8/MmmowkcNBqrEnOIk/2oF8iWvKrl7HofauTGZTqoPElc9z1W8+O\n"
    "wB34Jp9EI/oZLRlvqXc1aNSVSYCG3bcLLn4RRs237Dhl2RQGrMJrmYOYiGrUmO9n\n"
    "n2AhxgjSrMJllT0CAwEAAaNTMFEwHQYDVR0OBBYEFASU3NZqsSvPDSfVss6ljKv9\n"
    "kpVSMB8GA1UdIwQYMBaAFASU3NZqsSvPDSfVss6ljKv9kpVSMA8GA1UdEwEB/wQF\n"
    "MAMBAf8wDQYJKoZIhvcNAQELBQADggEBAACvPLsUqtA0eLU8Os2D5wvWtiBeKyhA\n"
    "2Bbt5iPrtyUCLQgMQ7ukqjHNW77C5P9hn7f086zcTmi1JLqccYKfWzr4Z+ne74a2\n"
    "aXurQ5oscs6/LWFz4cBkRUsUPPusgZp4Gc1Z6YojT8f4zH0rxhWtwOfesD44K8U1\n"
    "1AXViSsTQb5uyg0kSPr3BZnlNg+ZM45eLwnIoVnosdPWCR9mxo8uS1Mk7KKaHC0Y\n"
    "4XQuYh2CLVebNRLevBRxaczHDTQCo9zk4qxSbp3uLeO4iwnMFY5jHBd4BZTh8SzV\n"
    "czQp5NWesJbaCDbwSgIntz82VBxu+258t9NAkBfOmUEJcziB5r6PrW4=\n"
    "-----END CERTIFICATE-----\n"
};

const char *get_cert()
{
    return certStr;
}
